work in progress
AlbanyCanCodeCourses/PollingDataVisualization pull request #2
Opened 2019-05-04 16:59 UTC by ray-vazquez

2019-05-04 17:10 UTC, lindakovacs approved these changes

2019-05-05 01:05 UTC, gc-westover requested changes
Moving _assets_ outside of _src_ causes issues on compiling, since imports outside of _src_ are not allowed when using the create-react-app default setup. Moving it back should fix it, and not cause any other issues to my knowledge?

2019-05-07 01:58 UTC, ray-vazquez commented
moved assets dir outside of src.

2019-05-07 02:11 UTC, lindakovacs commented
I'm glad we cleared the confusion over the assets folder place between React and React Native.

2019-05-07 02:11 UTC, closed without merging